# Generated by Django 4.0.5 on 2022-06-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msafiri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('national_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
