# Generated by Django 4.0.5 on 2022-06-07 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(choices=[('NRB', 'Nairobi'), ('ELD', 'Eldoret'), ('NAK', 'Nakuru'), ('NAV', 'Naivasha'), ('NYR', 'Nyeri'), ('NYH', 'Nyahururu'), ('KIT', 'Kitale'), ('MAK', 'Makueni'), ('JUJ', 'Juja'), ('THK', 'Thika')], default=None, max_length=3)),
                ('end_point', models.CharField(choices=[('NRB', 'Nairobi'), ('ELD', 'Eldoret'), ('NAK', 'Nakuru'), ('NAV', 'Naivasha'), ('NYR', 'Nyeri'), ('NYH', 'Nyahururu'), ('KIT', 'Kitale'), ('MAK', 'Makueni'), ('JUJ', 'Juja'), ('THK', 'Thika')], default=None, max_length=3)),
                ('departure_time', models.TimeField()),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('seats', models.JSONField()),
                ('BUS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paid', models.DateField()),
                ('time_paid', models.TimeField()),
                ('seat_number', models.IntegerField()),
                ('payment_id', models.TextField()),
                ('ROUTE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.route')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.msafiri')),
            ],
        ),
    ]
